In [1]:
import cv2
from keras.models import load_model
import numpy as np
model = load_model('keras_model.h5')
cap = cv2.VideoCapture(0)
data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)

while True: 
    ret, frame = cap.read()
    resized_frame = cv2.resize(frame, (224, 224), interpolation = cv2.INTER_AREA)
    image_np = np.array(resized_frame)
    normalized_image = (image_np.astype(np.float32) / 127.0) - 1 # Normalize the image
    data[0] = normalized_image
    prediction = model.predict(data)
    cv2.imshow('frame', frame)

    print(prediction[0][0])
    print(prediction[0][1])
    print(prediction[0][2])
    print(prediction[0][3])

    if prediction[0][0] > 0.5:
        print("rock")
    elif prediction [0][1] > 0.5:
        print("paper")
    elif prediction [0][2] > 0.5:
        print ('Scissors')
    else:
        print("no prediction")
                
    # Press q to close the window
    print(prediction)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
            
# After the loop release the cap object
cap.release()
# Destroy all the windows
cv2.destroyAllWindows()

2022-06-11 17:22:14.392703: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/zain/miniconda3/envs/aicore_new/lib/python3.8/site-packages/cv2/../../lib64:
2022-06-11 17:22:14.392734: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2022-06-11 17:22:16.348507: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/zain/miniconda3/envs/aicore_new/lib/python3.8/site-packages/cv2/../../lib64:
2022-06-11 17:22:16.348558: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2022-06-11 17:22:16.348604: I tensorflow/stream_executor/cuda/cud

1/1 [==============================] - 1s 1s/step
1.1552469e-07
0.00024165465
0.9986553
0.0011029249
Scissors
[[1.1552469e-07 2.4165465e-04 9.9865532e-01 1.1029249e-03]]
1/1 [==============================] - 0s 42ms/step
8.314266e-09
0.00028726066
0.99923384
0.00047879835
Scissors
[[8.3142657e-09 2.8726066e-04 9.9923384e-01 4.7879835e-04]]


qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in "/home/zain/miniconda3/envs/aicore_new/lib/python3.8/site-packages/cv2/qt/plugins"


1/1 [==============================] - 0s 44ms/step
2.8825724e-07
0.00018104489
0.9992101
0.0006085788
Scissors
[[2.8825724e-07 1.8104489e-04 9.9921012e-01 6.0857879e-04]]
1/1 [==============================] - 0s 36ms/step
1.89449e-08
0.00018404351
0.99959534
0.00022054618
Scissors
[[1.8944901e-08 1.8404351e-04 9.9959534e-01 2.2054618e-04]]
1/1 [==============================] - 0s 34ms/step
4.8882356e-08
0.00012976523
0.9979171
0.0019531439
Scissors
[[4.8882356e-08 1.2976523e-04 9.9791712e-01 1.9531439e-03]]
1/1 [==============================] - 0s 32ms/step
1.5058113e-07
6.466006e-05
0.99937767
0.00055753347
Scissors
[[1.5058113e-07 6.4660060e-05 9.9937767e-01 5.5753347e-04]]
1/1 [==============================] - 0s 37ms/step
8.549444e-07
0.0003269832
0.99428445
0.0053876624
Scissors
[[8.5494440e-07 3.2698319e-04 9.9428445e-01 5.3876624e-03]]
1/1 [==============================] - 0s 35ms/step
1.4287676e-07
0.00010303121
0.9987405
0.0011563112
Scissors
[[1.4287676e-07 1.0303121e-0