In [1]:
import cv2
from keras.models import load_model
import numpy as np
model = load_model('keras_model.h5')
cap = cv2.VideoCapture(-1)
data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)

while True: 
    ret, frame = cap.read()
    resized_frame = cv2.resize(frame, (224, 224), interpolation = cv2.INTER_AREA)
    image_np = np.array(resized_frame)
    normalized_image = (image_np.astype(np.float32) / 127.0) - 1 # Normalize the image
    data[0] = normalized_image
    prediction = model.predict(data)
    cv2.imshow('frame', frame)
    # Press q to close the window
    print(prediction)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
            
# After the loop release the cap object
cap.release()
# Destroy all the windows
cv2.destroyAllWindows()

2022-06-08 10:15:24.069585: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/zain/miniconda3/envs/aicore_new/lib/python3.8/site-packages/cv2/../../lib64:
2022-06-08 10:15:24.069611: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2022-06-08 10:15:26.380006: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/zain/miniconda3/envs/aicore_new/lib/python3.8/site-packages/cv2/../../lib64:
2022-06-08 10:15:26.380036: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2022-06-08 10:15:26.380056: I tensorflow/stream_executor/cuda/cud

1/1 [==============================] - 1s 947ms/step


qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in "/home/zain/miniconda3/envs/aicore_new/lib/python3.8/site-packages/cv2/qt/plugins"


[[1.7422635e-05 4.4205957e-05 9.9980301e-01 1.3536288e-04]]
1/1 [==============================] - 0s 30ms/step


Qt: Session management error: Could not open network socket


[[5.3623771e-06 6.2665255e-05 9.9978596e-01 1.4595491e-04]]
1/1 [==============================] - 0s 33ms/step
[[5.0960301e-04 1.9042009e-04 9.9915218e-01 1.4783222e-04]]
1/1 [==============================] - 0s 68ms/step
[[7.6505478e-04 2.2217233e-04 9.9884355e-01 1.6924609e-04]]
1/1 [==============================] - 0s 35ms/step
[[5.2829820e-04 9.8648932e-05 9.9932849e-01 4.4565637e-05]]
1/1 [==============================] - 0s 32ms/step
[[2.8865644e-01 1.4584076e-03 7.0958394e-01 3.0117304e-04]]
1/1 [==============================] - 0s 34ms/step
[[2.3114055e-01 9.7419636e-04 7.6772189e-01 1.6335605e-04]]
1/1 [==============================] - 0s 34ms/step
[[2.3808861e-01 1.7067275e-03 7.5977826e-01 4.2635365e-04]]
1/1 [==============================] - 0s 33ms/step
[[1.0861986e-01 4.2742569e-04 8.9082700e-01 1.2576375e-04]]
1/1 [==============================] - 0s 34ms/step
[[1.5551548e-01 6.5183768e-04 8.4255546e-01 1.2772140e-03]]
1/1 [==============================] - 0s 34