In [1]:
import cv2
from keras.models import load_model
import numpy as np
model = load_model('keras_model.h5')
cap = cv2.VideoCapture(-1)
data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)

while True: 
    ret, frame = cap.read()
    resized_frame = cv2.resize(frame, (224, 224), interpolation = cv2.INTER_AREA)
    image_np = np.array(resized_frame)
    normalized_image = (image_np.astype(np.float32) / 127.0) - 1 # Normalize the image
    data[0] = normalized_image
    prediction = model.predict(data)
    cv2.imshow('frame', frame)
    # Press q to close the window
    print(prediction)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
            
# After the loop release the cap object
cap.release()
# Destroy all the windows
cv2.destroyAllWindows()

2022-06-08 16:36:58.767285: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/zain/miniconda3/envs/aicore_new/lib/python3.8/site-packages/cv2/../../lib64:
2022-06-08 16:36:58.767310: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2022-06-08 16:37:00.501872: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/zain/miniconda3/envs/aicore_new/lib/python3.8/site-packages/cv2/../../lib64:
2022-06-08 16:37:00.501907: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2022-06-08 16:37:00.501936: I tensorflow/stream_executor/cuda/cud

1/1 [==============================] - 1s 825ms/step


qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in "/home/zain/miniconda3/envs/aicore_new/lib/python3.8/site-packages/cv2/qt/plugins"


[[5.4241490e-08 4.8126153e-10 9.9948186e-01 5.1821262e-04]]
1/1 [==============================] - 0s 40ms/step


Qt: Session management error: Could not open network socket


[[3.7801928e-10 6.8002888e-11 9.9975735e-01 2.4264430e-04]]
1/1 [==============================] - 0s 45ms/step
[[4.2333927e-09 7.6019790e-10 9.9972337e-01 2.7666180e-04]]
1/1 [==============================] - 0s 35ms/step
[[1.5613891e-09 1.2402679e-11 9.9992466e-01 7.5362252e-05]]
1/1 [==============================] - 0s 29ms/step
[[6.5924988e-10 3.7354855e-11 9.9976820e-01 2.3186742e-04]]
1/1 [==============================] - 0s 35ms/step
[[1.7862149e-07 1.0654641e-09 9.9980110e-01 1.9872573e-04]]
1/1 [==============================] - 0s 39ms/step
[[1.5986841e-07 5.7521565e-10 9.9985075e-01 1.4915557e-04]]
1/1 [==============================] - 0s 35ms/step
[[2.486679e-08 8.338196e-10 9.999299e-01 7.013365e-05]]
1/1 [==============================] - 0s 40ms/step
[[7.1985191e-08 5.3902843e-10 9.9997568e-01 2.4142772e-05]]
1/1 [==============================] - 0s 42ms/step
[[2.9821162e-08 8.4790006e-09 9.9991715e-01 8.2850274e-05]]
1/1 [==============================] - 0s 33ms/s

KeyboardInterrupt: 