In [1]:
import cv2
from keras.models import load_model
import numpy as np
model = load_model('keras_model.h5')
cap = cv2.VideoCapture(-1)
data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)

while True: 
    ret, frame = cap.read()
    resized_frame = cv2.resize(frame, (224, 224), interpolation = cv2.INTER_AREA)
    image_np = np.array(resized_frame)
    normalized_image = (image_np.astype(np.float32) / 127.0) - 1 # Normalize the image
    data[0] = normalized_image
    prediction = model.predict(data)
    cv2.imshow('frame', frame)
    # Press q to close the window
    print(prediction)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
            
# After the loop release the cap object
cap.release()
# Destroy all the windows
cv2.destroyAllWindows()

2022-06-08 07:54:44.562985: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/zain/miniconda3/envs/aicore_new/lib/python3.8/site-packages/cv2/../../lib64:
2022-06-08 07:54:44.563014: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2022-06-08 07:54:47.060455: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/zain/miniconda3/envs/aicore_new/lib/python3.8/site-packages/cv2/../../lib64:
2022-06-08 07:54:47.060487: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2022-06-08 07:54:47.060512: I tensorflow/stream_executor/cuda/cud

1/1 [==============================] - 1s 863ms/step


qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in "/home/zain/miniconda3/envs/aicore_new/lib/python3.8/site-packages/cv2/qt/plugins"


[[4.7394460e-06 1.0972611e-02 8.4464842e-01 1.4437431e-01]]
1/1 [==============================] - 0s 32ms/step


Qt: Session management error: Could not open network socket


[[1.0817643e-06 4.5888163e-03 9.3473405e-01 6.0676102e-02]]
1/1 [==============================] - 0s 33ms/step
[[0.33285365 0.21520433 0.4345212  0.01742082]]
1/1 [==============================] - 0s 30ms/step
[[0.4174208  0.16309106 0.39168534 0.02780279]]
1/1 [==============================] - 0s 32ms/step
[[0.19060443 0.25427523 0.4908017  0.06431868]]
1/1 [==============================] - 0s 35ms/step
[[0.4937365  0.0054998  0.3732024  0.12756127]]
1/1 [==============================] - 0s 34ms/step
[[0.26796526 0.00480519 0.608014   0.11921553]]
1/1 [==============================] - 0s 33ms/step
[[0.47349542 0.00625845 0.24527049 0.27497563]]
1/1 [==============================] - 0s 34ms/step
[[0.10773407 0.00312996 0.67728424 0.21185175]]
1/1 [==============================] - 0s 30ms/step
[[0.06191842 0.00229734 0.7872324  0.14855188]]
1/1 [==============================] - 0s 31ms/step
[[0.04499108 0.00107996 0.9223937  0.03153525]]
1/1 [==============================] - 0